# Generated by Django 5.1 on 2024-09-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Article',
            new_name='article',
        ),
    ]
